### ISSUE TITLE
ValueError: Error raised by inference API HTTP code: 500, {"error":"error loading model 

### ISSUE THREAD

**Issue by holytony** [amscotti/local-LLM-with-RAG#5]
when I try to run the python app.py this is what I got, I have tried different models it's all the same ValueError: Error raised by inference API HTTP code: 500
```
Loading documents
Loading .pdf files
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:28<00:00, 28.23s/it]
Loading .md files
0it [00:00, ?it/s]
Creating embeddings and loading documents into Chroma
Traceback (most recent call last):
  File "******/local-LLM-with-RAG/app.py", line 122, in <module>
    main(args.model, args.embedding_model, args.path)
  File "******/local-LLM-with-RAG/app.py", line 67, in main
    db = load_documents_into_database(embedding_model_name, documents_path)
  File "******/local-LLM-with-RAG/app.py", line 49, in load_documents_into_database
    db = Chroma.from_documents(
  File "******/local-LLM-with-RAG/env/lib/python3.10/site-packages/langchain_community/vectorstores/chroma.py", line 778, in from_documents
    return cls.from_texts(
  File "******/local-LLM-with-RAG/env/lib/python3.10/site-packages/langchain_community/vectorstores/chroma.py", line 736, in from_texts
    chroma_collection.add_texts(
  File "******/local-LLM-with-RAG/env/lib/python3.10/site-packages/langchain_community/vectorstores/chroma.py", line 275, in add_texts
    embeddings = self._embedding_function.embed_documents(texts)
  File "******/local-LLM-with-RAG/env/lib/python3.10/site-packages/langchain_community/embeddings/ollama.py", line 204, in embed_documents
    embeddings = self._embed(instruction_pairs)
  File "******/local-LLM-with-RAG/env/lib/python3.10/site-packages/langchain_community/embeddings/ollama.py", line 192, in _embed
    return [self._process_emb_response(prompt) for prompt in iter_]
  File "******/local-LLM-with-RAG/env/lib/python3.10/site-packages/langchain_community/embeddings/ollama.py", line 192, in <listcomp>
    return [self._process_emb_response(prompt) for prompt in iter_]
  File "******/local-LLM-with-RAG/env/lib/python3.10/site-packages/langchain_community/embeddings/ollama.py", line 166, in _process_emb_response
    raise ValueError(
ValueError: Error raised by inference API HTTP code: 500, {"error":"error loading model /Users/****/.ollama/models/blobs/sha256:970aa74c0a90ef7482477cf803618e776e173c007bf957f635f1015bfcfef0e6"}
```

platform: Mac M1 MacOS 14.2.1
Ollama version:0.1.27

**Comment by holytony** [comment]
well, it somehow works after I have restart Ollama

**Comment by amscotti** [comment]
From the error message, it looks like the Ollama API wasn't up or something. Happy that restarting it worked.
