### ISSUE TITLE
Error when running app.py

### ISSUE THREAD

**Issue by An0nym0us30** [amscotti/local-LLM-with-RAG#6]
When I run app.py I get this error when I try to chat: 

```
Loading documents
Loading .pdf files
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.04it/s]
Loading .md files
0it [00:00, ?it/s]
Creating embeddings and loading documents into Chroma


Please enter your question (or type 'exit' to end): What is an agent?
Traceback (most recent call last):
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*******\Documents\local-LLM-with-RAG-main\app.py", line 122, in <module>
    main(args.model, args.embedding_model, args.path)
  File "C:\Users\*******\Documents\local-LLM-with-RAG-main\app.py", line 92, in main
    qa_chain.invoke({"query": user_input})
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 168, in invoke
    raise e
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 158, in invoke
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\retrieval_qa\base.py", line 144, in _call
    answer = self.combine_documents_chain.run(
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_core\_api\deprecation.py", line 145, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 555, in run
    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_core\_api\deprecation.py", line 145, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 383, in __call__
    return self.invoke(
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 168, in invoke
    raise e
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 158, in invoke
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\combine_documents\base.py", line 136, in _call
    output, extra_return_dict = self.combine_docs(
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\combine_documents\stuff.py", line 244, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\llm.py", line 293, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_core\_api\deprecation.py", line 145, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 383, in __call__
    return self.invoke(
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 168, in invoke
    raise e
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 158, in invoke
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\llm.py", line 103, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\llm.py", line 115, in generate
    return self.llm.generate_prompt(
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_core\language_models\llms.py", line 568, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_core\language_models\llms.py", line 741, in generate
    output = self._generate_helper(
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_core\language_models\llms.py", line 605, in _generate_helper
    raise e
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_core\language_models\llms.py", line 592, in _generate_helper
    self._generate(
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_community\llms\ollama.py", line 408, in _generate
    final_chunk = super()._stream_with_aggregation(
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_community\llms\ollama.py", line 317, in _stream_with_aggregation
    for stream_resp in self._create_generate_stream(prompt, stop, **kwargs):
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_community\llms\ollama.py", line 159, in _create_generate_stream
    yield from self._create_stream(
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_community\llms\ollama.py", line 220, in _create_stream
    response = requests.post(
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\*******\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
``` 

And when I try to run it again, I get this: 

```
C:\Users\*******\Documents\local-LLM-with-RAG-main>python app.py
[WinError 10061] No connection could be made because the target machine actively refused it
``` 

What's causing this error? Thanks.

**Comment by xyyimian** [comment]
same issue

**Comment by amscotti** [comment]
Do you have [Ollama](https://ollama.com/) up and running? None of my systems are running windows, so I'm unable to test this, but the only connection that the application is making is to the locally running Ollama server. Maybe give Ollama a restart to see if that helps.

**Comment by An0nym0us30** [comment]
I forgot to run the model beforehand, running `ollama run <model>` first and also updating ollama fixed the issue.
